# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
# TODO http://theaterbankvooruit.be
title:            Bank Vooruit
description:      Bank Vooruit speelt ACHT
tagline:          Een spannende interactieve familievoorstelling voor De Warmste Week
url:              /
baseurl:          https://bankvooruit.github.io
author:
  name:           Nele Rober

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/bankvooruit

# Global paths !! do not forget to change them in the .css files, the posts and down below !!
res-path:         https://bankvooruit.github.io/res
incl-path:        https://bankvooruit.github.io/inc