# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bank Vooruit
description:      Bank Vooruit QUIZT
tagline:          Een gezellige quiz met een stevig vleugje BankVooruit-kruiden.
url:              /
baseurl:          http://www.theaterbankvooruit.be
author:
  name:           Nele Rober

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/bankvooruit

# Global paths !! do not forget to change them in the .css files, the posts and down below !!
res-path:         http://www.theaterbankvooruit.be/res
incl-path:        http://www.theaterbankvooruit.be/inc

# Scss
sass:
  style: compressed