# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bank Vooruit
description:      Bank Vooruit speelt De Code van de Kaart
tagline:          Een spannenede familievoorstelling voor het goede doel.
url:              /
baseurl:          https://www.theaterbankvooruit.be
author:
  name:           Nele Rober

# Custom vars
version:          1.0.0
github:           [metadata]

# Global paths !! do not forget to change them in the .css files, the posts and down below !!
res-path:         https://www.theaterbankvooruit.be/res
incl-path:        https://www.theaterbankvooruit.be/inc

# Scss
sass:
  style: compressed